# PyPEEC options for the 2D plots (using Matplotlib).
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

"style": "default"         # string with a Matplotlib style
"legend": "best"           # location of the legend box
"font": 12                 # reference font size of the figure
